### ISSUE TITLE
Upgrade 6.1.0 -> 6.2.0 - datatype "calculated column" is missing

### ISSUE THREAD

**Issue by mcshorty** [DNNCommunity/DNN.FormAndList#5] opened 2016-05-07 16:11 UTC
After upgrading from 6.1.0 -> 6.2.0 (DNN 8.0.1) the datatype "calculated column" is missing.

**Comment by sleupold** [comment] 2016-05-19 10:21
this seems to be caused by a modified entry in dataType.config.
The last entry should be just   <dataType name="Expression" />

**Comment by SCullman** [comment] 2016-12-07 17:26
Well, it should have been  
`<dataType name="Expression" typeName="DotNetNuke.Modules.UserDefinedTable.DataTypes.DataTypeExpessionEmail"/>`

**Comment by sleupold** [comment] 2016-12-07 17:47
seem to be fixed by DNN Corp. already.

**Comment by SCullman** [comment] 2018-06-09 13:19
FIXED

**Comment by valadas** [comment] 2018-06-16 08:42
@EPTamminga , please close this one too

**Closed** 2018-06-16 12:43 UTC
