### ISSUE TITLE
Cannot Select Folder to Import/Export Data

### ISSUE THREAD

**Issue by kaneluong** [DNNCommunity/DNN.FormAndList#64] opened 2019-09-17 20:46 UTC
## Describe the bug
Cannot select folder to export or import data. The only option in the dropdown is <None Specified>. Is there a fix for this?

**Comment by SCullman** [comment] 2019-09-19 19:27
I cannot reproduce.
![image](https://user-images.githubusercontent.com/5693190/65274578-ec852d80-db23-11e9-8694-9a29389f58a1.png)
Your user needs READ and WRITE permissions on the folder, otherwise they are not listed.

**Comment by SCullman** [comment] 2019-09-19 19:31
same for Export Content:
![image](https://user-images.githubusercontent.com/5693190/65274931-c449fe80-db24-11e9-9c83-9b73c0874cc0.png)

**Comment by kaneluong** [comment] 2019-09-19 20:11
I have read and write permissions at the root of the folder. It still doesn’t work.

What folder are you adding the read and write permissions?

**Comment by SCullman** [comment] 2019-09-19 20:22
Any folder you want to see in that list.
(As administrator, you should see every folder here.)

**Comment by kaneluong** [comment] 2019-09-19 20:42
The permissions are correct. I still don't see it. I only see the folders if I export/import the content. 

I'm using version 6.5.3 of Form and List.

I even tried it on a clean install of DNN 9.4 with all permissions set up correctly and I only the see folder if I export/import the content.

**Comment by SCullman** [comment] 2019-09-20 22:02
Well, I can reproduce on DNN 9.4.0.
All folders crated by default are not initialized with proper permissions. Go to any of them in `Manage-Site Assets`. Right click on folder, open `View Folder Permissions`. Go to tab `Permissions`. Do nothing but to click button `Save`.

Go back to Form and List. The folder will appear now in `Export to Csv`.
This can't be solved here in the scope of the module.

**Comment by valadas** [comment] 2019-09-24 08:56
This has been reported a number of times in the platform repository (see https://github.com/dnnsoftware/dnn.platform

But none of the reports I have seen had reproducible steps, this appears to be bound to some environmental factors or some combination of upgrades, etc. For that reason I am closing this issues here.

**Comment by SCullman** [comment] 2019-09-24 10:31
As long as this is not fixed in DNN 9.4., this issue should stay open.

**Comment by valadas** [comment] 2019-09-24 10:38
Cool

**Comment by SCullman** [comment] 2019-09-24 21:28
This is weird. But now, after 4 more  DNN9.4 installations, I know now what is happening. 🤦‍♂️

**Comment by SCullman** [comment] 2019-09-24 21:31
And now this can be closed!

**Closed by SCullman** 2019-09-24 21:31 UTC

**Comment by kaneluong** [comment] 2019-09-24 22:35
I'm assuming that the fix will be released on the 9.4.1 version? As of now, we should just do the work around on what you mentioned?

**Comment by SCullman** [comment] 2019-09-24 22:54
Just use the `Default Website.template` instead the `Blank Website.template` and delete any unwanted content. Or do the workaround as described.
If the fix will be included in DNN 9.4.1 is out of my control.

**Comment by valadas** [comment] 2019-10-16 01:37
PR got merged, so this should be fixed when Dnn 9.4.2 gets out
