### ISSUE TITLE
FnL 6.2.0 on DNN 8: Results are not displayed 

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/DNN.FormAndList#12] opened 2016-10-15 15:10 UTC
In form mode, there is an option to display all records, which is simply not working in this version. No error logged.

**Comment by DotNetNuclear** [comment] 2016-10-31 03:14
Sebastian, I confirmed the "Show Records" button at the bottom of the Form view does the same thing as the "Show Records" module action menu item.  It should redirect you to the /show/records List module view.  It works for me.  Can you provide any more details?

**Comment by SCullman** [comment] 2018-06-09 13:30
CANNOT reproduce

**Comment by valadas** [comment] 2018-06-16 21:19
I cannot reproduce in latest build either, I will close this, @sleupold feel free to reopen or submit a new issue if not resolved

**Closed by valadas** 2018-06-16 21:19 UTC
