### ISSUE TITLE
Sorting fails with URL rewriter when using Generated XSLT 

### ISSUE THREAD

**Issue by 17Neurons** [DNNCommunity/DNN.FormAndList#78] opened 2020-10-02 04:31 UTC
## Describe the bug
DNN 9.3.2 FnL 6.5.3 ... Using generated XSLT grid, sorting option on. When the URL gets rewritten to friendly, FnL sorting string starts to duplicate. It appends querystring on querystring, converting to friendly each time. Works on first click but fails on all after. 

## To Reproduce
1. Setup a FnL grid using XSLT generated table. Add headers for sorting.
2. Save the xslt, view page and click on a sorting header.

Url example 1 - original page
http://somedomain.com/Roster/
Url example 2 - after 1st sorting click
http://somedomain.com/Roster/udt_4587_param_orderby/Position/udt_4587_param_direction/ascending
Url example 3 - after 2nd sorting click
http://somedomain.com/Roster/udt_4587_param_orderby/Position/udt_4587_param_direction/ascending?udt_4587_param_orderby=Position&udt_4587_param_direction=descending

## Expected behavior
Should sort asc/desc each time

## Error log
No error generated

## Additional context
I also have the EasyDNN Url Rewriter installed. Clearly a rewrite problem.

**Comment by valadas** [comment] 2021-02-13 23:53
I cannot reproduce this issue with F&L 6.5.4 on Dnn 9.8.1 

My guess is either it was fixed in Dnn or the latest version of this module or is related to specific friendly urls settings. If you have more informaiton after upgrading both please open a new issue.

**Closed by valadas** 2021-02-13 23:53 UTC
