### ISSUE TITLE
Value cannot be null. Parameter name: type

### ISSUE THREAD

**Issue by fprati** [DNNCommunity/DNN.FormAndList#9] opened 2016-08-08 16:35 UTC
Release 6.2.0 on dnn 8.0.3.
It happens randomly, the form and all other html modules on the page look blank; page refresh does not help. One has to go to a different page and back to see the form and the rest of the page working again. Here is the log message:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7c7b50e8-eaf3-4c3b-8ca5-4a66b01c28b3
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:uQ+8ZRsItfjnKYfnr2T38g==
Message:Value cannot be null. Parameter name: type
StackTrace:
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes()
   at DotNetNuke.Modules.UserDefinedTable.DataType.ByName(String dataTypeName)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.Modules.UserDefinedTable.Default.LoadControlByKey(String controlKey)
   at DotNetNuke.Modules.UserDefinedTable.Default.InitViews()
   at DotNetNuke.Modules.UserDefinedTable.Default.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by jhaggerty21** [comment] 2016-10-03 16:55
We are having the same exact issue, did anyone find a fix for this?

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:bffb7fde-f851-4a54-861c-89a748bb79c6
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:t1Xw7QcmlYMBNpKTcBT9FQ==
Message:Unhandled Error Adding Module to rightPane2.
StackTrace:
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
InnerMessage:Value cannot be null. Parameter name: type
InnerStackTrace:
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes()
   at DotNetNuke.Modules.UserDefinedTable.DataType.ByName(String dataTypeName)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.Modules.UserDefinedTable.Default.LoadControlByKey(String controlKey)
   at DotNetNuke.Modules.UserDefinedTable.Default.InitViews()
   at DotNetNuke.Modules.UserDefinedTable.Default.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)

Thanks,

**Comment by fprati** [comment] 2016-10-03 17:49
Hi, not that I know, but if it may help here is a workaround that works for me: 
1. Set delay to 0
2. Keep alive the website, i.e., never let the app pool swap to disk. Reboot once a week just in case you develop memory leaks.

**Comment by RSSLLC** [comment] 2016-10-03 21:26
Hi Everyone, has anyone heard any updates on this issue?  We have a large client that started experiencing it today with a new form (a large one, unfortunately).  Thanks, Todd

**Comment by DotNetNuclear** [comment] 2016-10-03 21:55
I will try to reproduce this tonight and will give an update.

**Comment by RSSLLC** [comment] 2016-10-03 21:58
Awesome, thanks!  If you need an example page I can supply a URL from our customer site.  Here is the fatal error from the DNN log:

2016-10-03 17:53:53,705 [*SERVERNAME*][Thread:67][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.ArgumentNullException: 'dataType' argument cannot be null.
Parameter name: dataType
   at System.Data.DataColumn..ctor(String columnName, Type dataType, String expr, MappingType type)
   at System.Data.DataColumn..ctor(String columnName, Type dataType)
   at DotNetNuke.Common.Globals.BuildCrossTabDataSet(String DataSetName, IDataReader result, String FixedColumns, String VariableColumns, String KeyColumn, String FieldColumn, String FieldTypeColumn, String StringValueColumn, String NumericValueColumn, CultureInfo Culture)
   at DotNetNuke.Modules.UserDefinedTable.UserDefinedTableController.BuildMainDataSet(DataTable fieldsTable, IDataReader dr, Boolean rowMode)
   at DotNetNuke.Modules.UserDefinedTable.UserDefinedTableController.GetRow(Int32 userDefinedRowId, Boolean withPreRenderedValues, Boolean filterScript)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.get_Data()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2016-10-03 17:53:53,705 [*SERVERNAME*][Thread:67][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=3881&error=%27dataType%27+argument+cannot+be+null.%0d%0aParameter+name%3a+dataType&content=0
System.ArgumentNullException: 'dataType' argument cannot be null.
Parameter name: dataType
   at System.Data.DataColumn..ctor(String columnName, Type dataType, String expr, MappingType type)
   at System.Data.DataColumn..ctor(String columnName, Type dataType)
   at DotNetNuke.Common.Globals.BuildCrossTabDataSet(String DataSetName, IDataReader result, String FixedColumns, String VariableColumns, String KeyColumn, String FieldColumn, String FieldTypeColumn, String StringValueColumn, String NumericValueColumn, CultureInfo Culture)
   at DotNetNuke.Modules.UserDefinedTable.UserDefinedTableController.BuildMainDataSet(DataTable fieldsTable, IDataReader dr, Boolean rowMode)
   at DotNetNuke.Modules.UserDefinedTable.UserDefinedTableController.GetRow(Int32 userDefinedRowId, Boolean withPreRenderedValues, Boolean filterScript)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.get_Data()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by DotNetNuclear** [comment] 2016-10-04 02:42
Based on your descriptions, it appears to be a concurrency issue.  Having a hard time recreating.  Can you share your datatype.config with me?  It is either in /Portals/_default/UserDefinedTable/datatypes.config OR /DesktopModules/UserDefinedTable/datatypes.config.

**Comment by RSSLLC** [comment] 2016-10-04 02:46
Sure thing, here it is:

<dataTypes> 
  <dataType name="CreatedBy" />
  <dataType name="CreatedAt" />
  <dataType name="ChangedBy" />
  <dataType name="ChangedAt" />
  
  
  <dataType name="String" />
  <dataType name="Int32" />
  <dataType name="Decimal" />
  <dataType name="DateTime" />
  <dataType name="Date" />
  <dataType name="Time" />
  <dataType name="Boolean" />
  <dataType name="EMail" />
  <dataType name="Currency" />
  <dataType name="URL" />
  <dataType name="Image" />
  <dataType name="TextHtml" />
  <dataType name="Download" />
  <dataType name="UserLink" />
  <dataType name="Separator" />
  
  <dataType name="LookUp" />
  <dataType name="Expression" typeName="DataTypeExpessionEmail"/>
</dataTypes>

I did try removing the typeName="DataTypeExpessionEmail" entry and restarting the app pool and site based on an article I found, but that did not have any affect.

**Comment by RSSLLC** [comment] 2016-10-04 02:48
[datatypes.config.txt](https://github.com/DNNCommunity/DNN.FormAndList/files/507586/datatypes.config.txt)

**Comment by DotNetNuclear** [comment] 2016-10-04 03:33
Try using this file.  I am looking at better ways to cache the data types as well.

[datatypes.config.txt](https://github.com/DNNCommunity/DNN.FormAndList/files/507633/datatypes.config.txt)

**Comment by RSSLLC** [comment] 2016-10-04 04:04
Thanks.  Unfortunately that does not appear to have worked.  Same error.  Todd

**Comment by RSSLLC** [comment] 2016-10-04 04:06
Quick note, all of the other forms we have created in this customer's DNN instance are working properly (if that helps).

**Comment by DotNetNuclear** [comment] 2016-10-04 12:39
Todd, can you send me a link to the form that is not working?  I may need more information about the field configuration or data.

**Comment by RSSLLC** [comment] 2016-10-04 12:45
Sure thing, here it is:  http://www.caslnc.com/Club-Survey-Fall-2016

One unique thing about the form is that the customer created some very long field titles.  I have tried changing some (but not all) of them in the database itself as a test, but so far no luck.

**Comment by DotNetNuclear** [comment] 2016-10-04 13:01
Todd, can you provide me a screenshot of the field configuration?  As an anonymous user, I can only see the exception.

**Comment by RSSLLC** [comment] 2016-10-04 13:27
Unfortunately we cannot get into the configuration of that copt of the F&L module (due to the module load error), but I have attached that specific forms details from the UserDefiniedFields and UserDefinedFieldSettings tables for that specific module if that helps.
[FormAndListModuleErrorFieldsAndSettings.xlsx](https://github.com/DNNCommunity/DNN.FormAndList/files/508542/FormAndListModuleErrorFieldsAndSettings.xlsx)

**Comment by DotNetNuclear** [comment] 2016-10-04 13:56
Todd,

Thank you.
I was able to recreate the issue.  I will make a fix in code, but the workaround is this:

There were a couple fields named "Optional Comments" that have '|' pipe characters in the name, ie "| Optional Comments |".  If you get rid of the pipe characters, the exception goes away.  The pipe is used internally as a delimiter.  I will evaluate a fix to either disallow using pipe character in the UI, or escape it in the backend.

**Comment by DotNetNuclear** [comment] 2016-10-31 03:39
The fix will be in the next release.  Unfortunately, because of using a core DNN function that requires the pipes, I could only add validation to the Title field to keep you from adding the pipe character.  If there are pipe characters in existing forms, they may need to be dealt with in the database.

**Comment by SCullman** [comment] 2018-06-09 13:37
BUG: **Disallow** or escape Pipes in fieldname

**Comment by valadas** [comment] 2018-06-16 21:13
@DotNetNuclear @SCullman What is the status on this issue, was it done already or are you submitting a pull request or it is something I can tackle?

**Closed** 2018-06-17 08:27 UTC
Labels: bug
