### ISSUE TITLE
Porto 2 and Owl Carousel - DNN 8 Forms and List

### ISSUE THREAD

**Issue by epochonline** [DNNCommunity/DNN.FormAndList#3] opened 2016-05-03 19:18 UTC
"We are experiencing an "Owl Carousel problem" when we install the beta DNN 8 module Forms and Lists along with Mandeeps Porto 2 skin with Owl Carousel on IE.

Basically, we are using Porto 2 as a skin and as a part of a couple of HTML module's content we've deployed Owl Carousel using Porto's shortcodes to run the Owl Carousel. Everything was working fine before we installed F and L and added a form to the same pages. Where we used to see the Owl Carousel, we nothing. This only happens when using IE as the browser. We've tried searching for this issue but have not been able to find anything related.  Can you help?

**Comment by TonyValenti** [comment] 2016-09-26 11:15
This is related to $(...).dnnPanels is not a function

**Comment by SCullman** [comment] 2018-06-09 13:19
FIXED

**Comment by valadas** [comment] 2018-06-16 08:40
@EPTamminga sorry to bother you again, but can you also close this one since it is fixed. Thanks.

**Comment by EPTamminga** [comment] 2018-06-16 12:44
@valadas : No problem. I would like to give you the rights to close issues yourself, but I do not have the rights here to manage rights of others.

**Closed by EPTamminga** 2018-06-16 12:44 UTC

**Comment by SCullman** [comment] 2018-06-16 13:58
@EPTamminga, who can manage rights of others here?

**Comment by EPTamminga** [comment] 2018-06-16 15:10
I think the owner of a team (there are 3 teams here in this Organization and 2 owners, JoeB is owner in all teams).

https://github.com/orgs/DNNCommunity/people

**Comment by valadas** [comment] 2018-06-16 17:21
@SCullman , @EPTamminga I just got the rights from Clint today, so I should stop bothering your guys with those requests. I am just trying to tidy up old resolved or not-reproducible issues.

**Comment by EPTamminga** [comment] 2018-06-16 20:29
@valadas: great! Keep going!

**Comment by valadas** [comment] 2018-06-17 04:55
@EPTamminga awesome, just found a way to get in touch with the whole team
