### ISSUE TITLE
Is not possible to change "Displayed text after form post" after form creation

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#59] opened 2019-04-24 18:51 UTC
## Describe the bug
After you create a form and set some info, if you try to update the "Displayed text after form post" field in CKEditor, changes are not saved

## To Reproduce
1. Create a form and finish some settings
2. Try to change "Displayed text after form post" field in CKEditor
3. Save

Changes are not saved. If you edit again, you will see the same default text

## Expected behavior

You should be able to save new value for "Displayed text after form post" field

**Comment by SCullman** [comment] 2019-08-10 11:00
I cannot reproduce. My changes are saved.

**Comment by ufoloko** [comment] 2019-08-11 03:23
First time you create form and set text is correctly saved. But if you edit form later and try to change text, you are not able to save

**Comment by SCullman** [comment] 2019-08-11 09:36
I did change that text this morning again. And yes, it was saved.   
Tested within DNN 9.3.2 / CK Editor 1.0.5.

**Comment by ufoloko** [comment] 2019-09-09 03:30
I just tried to make changes but it appears ckeditor value is not changing when save. If you use plain Text editor,  value is saved correctly, for some reason ckeditor mode have some issue.

En version is 9.3.2

**Comment by SCullman** [comment] 2019-09-09 07:56
@ufoloko, I believe you. Anyway, I can not reproduce. I bet if you test on a fresh DNN 9.3.2  installation, using the default skin, it would work for you either.

I am sorry. Strictly speaking, this is not an issue of this module. This happens in your setup. Do you see any errors in logs or browser console?

**Comment by valadas** [comment] 2021-02-13 23:01
I am closing this issue due to no progress in over a year

**Closed by valadas** 2021-02-13 23:01 UTC
